# Generated by Django 3.0.8 on 2020-08-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDRCreated', models.DateTimeField(auto_created=True)),
                ('PDRName', models.CharField(max_length=100)),
                ('PDRDesc', models.TextField()),
                ('PDRPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PDRCost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
