# Generated by Django 3.1 on 2020-08-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PDRCost',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PDRCreated',
            field=models.DateTimeField(auto_created=True, verbose_name='Product created at '),
        ),
        migrations.AlterField(
            model_name='product',
            name='PDRDesc',
            field=models.TextField(verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PDRName',
            field=models.CharField(max_length=100, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PDRPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Price'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDImage', models.ImageField(upload_to='products/')),
                ('PRDID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
